#!/bin/bash
# Kubernetes on AWS (1 Control Plane + 1 Worker Node)
# Open this file in VS Code and run sections step by step.
# Replace placeholders before use.

############################
# SECTION 1 - RUN ON BOTH NODES
############################
# Disable swap
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# Kernel modules
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF
sudo modprobe overlay
sudo modprobe br_netfilter

# Sysctl
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF
sudo sysctl --system

# Install containerd
curl -LO https://github.com/containerd/containerd/releases/download/v1.7.14/containerd-1.7.14-linux-amd64.tar.gz
sudo tar Cxzvf /usr/local containerd-1.7.14-linux-amd64.tar.gz
curl -LO https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
sudo mkdir -p /usr/local/lib/systemd/system/
sudo mv containerd.service /usr/local/lib/systemd/system/
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
sudo systemctl daemon-reload
sudo systemctl enable --now containerd

# Install runc
curl -LO https://github.com/opencontainers/runc/releases/download/v1.1.12/runc.amd64
sudo install -m 755 runc.amd64 /usr/local/sbin/runc

# Install CNI plugins
curl -LO https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz
sudo mkdir -p /opt/cni/bin
sudo tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.5.0.tgz

# Install kubeadm kubelet kubectl
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl gpg
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubelet=1.29.6-1.1 kubeadm=1.29.6-1.1 kubectl=1.29.6-1.1
sudo apt-mark hold kubelet kubeadm kubectl
sudo crictl config runtime-endpoint unix:///var/run/containerd/containerd.sock

############################
# SECTION 2 - CONTROL PLANE ONLY
############################
# Replace 10.0.0.X with control plane private IP
sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=10.0.0.X

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

kubectl get nodes -o wide

#list all containers:
sudo crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a

# Install Calico
kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
curl -O https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
kubectl apply -f custom-resources.yaml


kubectl get pods -A

############################
# SECTION 3 - WORKER NODE ONLY
############################
# Run join command generated by control plane
# kubeadm token create --print-join-command
sudo kubeadm join <master-node-ip>:6443 --token <your-token> \
--discovery-token-ca-cert-hash sha256:<your-hash>

############################
# SECTION 4 - VERIFY FROM CONTROL PLANE
############################
kubectl get nodes -o wide
  


# Re connect cluster
# Update the server IP in kubeconfig
sudo sed -i 's|https://44.204.121.209:6443|https://100.55.130.50:6443|g' ~/.kube/config

# Verify it updated correctly
grep server ~/.kube/config


# Run this on your control plane and copy the output
cat ~/.kube/config


kubectl config view --raw | \
  sed 's|certificate-authority-data:.*|insecure-skip-tls-verify: true|g' | \
  sed '/certificate-authority-data/d'


  Step 1 — Switch back to the private IP for local use:
bashsudo sed -i 's|https://100.55.130.50:6443|https://10.0.0.40:6443|g' ~/.kube/config
Step 2 — Test it works:
bashkubectl get svc -n tictactoe
This should now work because you're ON the control plane itself, so it can reach 10.0.0.40 directly (the private IP).

Then patch the service to NodePort:
bashkubectl patch svc tictactoe-svc -n tictactoe \
  -p '{"spec": {"type": "NodePort", "ports": [{"port": 80, "targetPort": 5000, "nodePort": 30080}]}}'
Check it:
bashkubectl get svc -n tictactoe
kubectl get pods -n tictactoe